# Copyright (c) 2025 Robert Bosch GmbH
# SPDX-License-Identifier: AGPL-3.0

defaults:
  - _self_
  - gripper: panda
  - object: subset_from_fast
  - env: clutter_table

id: 0

hydra:
  job:
    chdir: False
