# Copyright (c) 2025 Robert Bosch GmbH
# SPDX-License-Identifier: AGPL-3.0

defaults:
  - _self_
  - gripper: google
  - sampler: antipodal

num_grasps: 10
stats: False
object_id: "011_banana"

hydra:
  job:
    chdir: False
