# Copyright (c) 2025 Robert Bosch GmbH
# SPDX-License-Identifier: AGPL-3.0

defaults:
  - _self_
  - gripper: allegro
  - object: subset_from_fast
  - env: clutter_table

num_objects: 5
only_collision_free: False
save_collision_grasps: False

hydra:
  job:
    chdir: False
