defaults:
  - _self_
  - gripper: shadow

max_rounds: 100

# num target grasps to compute (will be checked in beginning)-> if enough exit
target_grasps: 2000

# collect grasps on sampling
sample_grasps: 2000

# num grasps to collect from sampling + collision filtering till stability eval.
collect_grasps_till_eval: 100

# num grasps to collect till save
collect_grasps_till_save: 100

# object id name
object_id: 0

# force per impulse
force: 100.0

hydra:
  job:
    chdir: False
