# Copyright (c) 2025 Robert Bosch GmbH
# SPDX-License-Identifier: AGPL-3.0

name: "GoogleGripper"
id: "google"
qpos: [0.01, 0.01] # open
qpos_close: [1.0, 1.0] # close
grasp_type: "default"
segmentation:
  left_finger: [2, 7]
  right_finger: [14, 19]
  body: [0, 1, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18]

eta: 7000
