# Copyright (c) 2025 Robert Bosch GmbH
# SPDX-License-Identifier: AGPL-3.0

name: "PandaGripper"
id: "panda"
qpos: [0.04, 0.00] # open
qpos_close: [0.0, -0.04] # close
grasp_type: "default"
segmentation:
  left_finger: [6, 7]
  right_finger: [14, 15]
  body: [0, 1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 13]

eta: 7000
