name: "StaticShadowHand"
id: "shadow_static"
grasp_sampler: "Antipodal"

segmentation:
  ff_j4: [15, 17, 19, 21]
  ff_j3: [17, 19, 21]
  ff_j2: [19, 21]
  ff_j1: [21]
  mf_j4: [23, 25, 27, 29]
  mf_j3: [25, 27, 29]
  mf_j2: [27, 29]
  mf_j1: [29]
  rf_j4: [31, 33, 35, 37]
  rf_j3: [33, 35, 37]
  rf_j2: [35, 37]
  rf_j1: [37]
  lf_j5: [39, 41, 43, 45, 47]
  lf_j4: [41, 43, 45, 47]
  lf_j3: [43, 45, 47]
  lf_j2: [45, 47]
  lf_j1: [47]
  th_j5: [50, 53, 56]
  th_j4: [50, 53, 56]
  th_j3: [53, 56]
  th_j2: [53, 56]
  th_j1: [56]
  palm:
    [
      0,
      6,
      15,
      17,
      19,
      21,
      23,
      25,
      27,
      29,
      31,
      33,
      35,
      37,
      39,
      41,
      43,
      45,
      47,
      50,
      53,
      56,
    ]
